bq-dbt-workshop:
  outputs:
    dev:
      dataset: dbt_eguzman
      fixed_retries: 1
      keyfile: /Users/og/Desktop/brilliant-balm-379703-2c88b124b216.json
      location: EU
      method: service-account
      priority: interactive
      project: brilliant-balm-379703
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev